import mongoose from "mongoose";
import Property from "./models/Properties.js";
import dotenv from "dotenv";
dotenv.config();
const MONGO_URI = process.env.MONGO_URI;
const DEFAULT_USER_ID = new mongoose.Types.ObjectId("69d0f13c9c0c141907262861");


const propertiesData = [
  {
    title: "Rajpur Road Luxury PG",
    city: "Dehradun",
    locality: "Rajpur Road",
    type: "pg",
    rent: 12000,
    foodCharges: 3500,
    deposit: 24000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Laundry", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.7, food: 4.4, owner: 4.8, wifi: 4.5 },
    reviews: [{ name: "Aarav", comment: "Bahut achhi jagah hai, saaf suthra", rating: 5 }],
    ownerName: "Suresh Negi",
    ownerPhone: "9012340001",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Patel Nagar Girls PG",
    city: "Dehradun",
    locality: "Patel Nagar",
    type: "pg",
    rent: 8500,
    foodCharges: 2500,
    deposit: 17000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Female",
    amenities: ["WiFi", "Meals", "Power Backup", "Housekeeping"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600"],
    safety: { cctv: true, guard: true, biometric: false },
    ratings: { room: 4.5, food: 4.3, owner: 4.7, wifi: 4.0 },
    reviews: [{ name: "Divya", comment: "Safe and homely feeling", rating: 5 }],
    ownerName: "Kamla Rawat",
    ownerPhone: "9012340002",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Dalanwala Boys Hostel",
    city: "Dehradun",
    locality: "Dalanwala",
    type: "pg",
    rent: 7000,
    foodCharges: 2000,
    deposit: 14000,
    roomType: "Triple",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Laundry", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600"],
    safety: { cctv: true, guard: false, biometric: false },
    ratings: { room: 4.0, food: 4.1, owner: 4.2, wifi: 3.8 },
    reviews: [{ name: "Rohit", comment: "Budget friendly, khana accha hai", rating: 4 }],
    ownerName: "Mohan Bisht",
    ownerPhone: "9012340003",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "ISBT Road Premium PG",
    city: "Dehradun",
    locality: "ISBT Road",
    type: "pg",
    rent: 9500,
    foodCharges: 3000,
    deposit: 19000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Laundry"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.4, food: 4.2, owner: 4.6, wifi: 4.3 },
    reviews: [{ name: "Pankaj", comment: "Connectivity bahut acchi hai", rating: 4 }],
    ownerName: "Deepak Thapliyal",
    ownerPhone: "9012340004",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Vasant Vihar Executive PG",
    city: "Dehradun",
    locality: "Vasant Vihar",
    type: "pg",
    rent: 13000,
    foodCharges: 3800,
    deposit: 26000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Parking", "Housekeeping"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.9, food: 4.6, owner: 4.9, wifi: 4.7 },
    reviews: [{ name: "Shruti", comment: "Ekdum top class PG, ek number!", rating: 5 }],
    ownerName: "Anil Chauhan",
    ownerPhone: "9012340005",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Clock Tower Area PG",
    city: "Dehradun",
    locality: "Paltan Bazaar",
    type: "pg",
    rent: 7500,
    foodCharges: 2200,
    deposit: 15000,
    roomType: "Double",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600"],
    safety: { cctv: true, guard: false, biometric: false },
    ratings: { room: 3.9, food: 4.0, owner: 4.1, wifi: 3.7 },
    reviews: [{ name: "Gaurav", comment: "Market ke paas, sab kuch paas mein", rating: 4 }],
    ownerName: "Raju Bhandari",
    ownerPhone: "9012340006",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Ballupur Chowk Girls PG",
    city: "Dehradun",
    locality: "Ballupur",
    type: "pg",
    rent: 9000,
    foodCharges: 2800,
    deposit: 18000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Female",
    amenities: ["WiFi", "AC", "Meals", "Laundry", "Housekeeping"],
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.5, food: 4.4, owner: 4.8, wifi: 4.2 },
    reviews: [{ name: "Neha", comment: "Bahut safe hai, madam bahut acchi hain", rating: 5 }],
    ownerName: "Geeta Negi",
    ownerPhone: "9012340007",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Sahastradhara Road PG",
    city: "Dehradun",
    locality: "Sahastradhara Road",
    type: "pg",
    rent: 10000,
    foodCharges: 3000,
    deposit: 20000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Parking"],
    images: ["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600"],
    safety: { cctv: true, guard: false, biometric: true },
    ratings: { room: 4.6, food: 4.2, owner: 4.7, wifi: 4.4 },
    reviews: [{ name: "Vikas", comment: "Pahad ka view milta hai, bahut sunder", rating: 5 }],
    ownerName: "Harish Rana",
    ownerPhone: "9012340008",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Rispana Pull Boys PG",
    city: "Dehradun",
    locality: "Rispana",
    type: "pg",
    rent: 6500,
    foodCharges: 1800,
    deposit: 13000,
    roomType: "Triple",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600"],
    safety: { cctv: false, guard: true, biometric: false },
    ratings: { room: 3.8, food: 3.9, owner: 4.0, wifi: 3.5 },
    reviews: [{ name: "Ankit", comment: "Sasta aur theek thaak jagah", rating: 3 }],
    ownerName: "Jagdish Semwal",
    ownerPhone: "9012340009",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "GMS Road Corporate PG",
    city: "Dehradun",
    locality: "GMS Road",
    type: "pg",
    rent: 11000,
    foodCharges: 3200,
    deposit: 22000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Laundry", "Parking"],
    images: ["https://images.unsplash.com/photo-1556009411-6df2ab6c5928?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.5, food: 4.1, owner: 4.6, wifi: 4.5 },
    reviews: [{ name: "Sumit", comment: "IT professionals ke liye perfect", rating: 5 }],
    ownerName: "Praveen Dimri",
    ownerPhone: "9012340010",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Nehru Colony Affordable PG",
    city: "Dehradun",
    locality: "Nehru Colony",
    type: "pg",
    rent: 6000,
    foodCharges: 1700,
    deposit: 12000,
    roomType: "Triple",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Laundry"],
    images: ["https://images.unsplash.com/photo-1600210492493-0946911123ea?w=600"],
    safety: { cctv: true, guard: false, biometric: false },
    ratings: { room: 3.7, food: 3.8, owner: 4.0, wifi: 3.6 },
    reviews: [{ name: "Deepak", comment: "Students ke liye sahi hai", rating: 4 }],
    ownerName: "Ramesh Gupta",
    ownerPhone: "9012340011",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "EC Road Girls Hostel",
    city: "Dehradun",
    locality: "EC Road",
    type: "pg",
    rent: 8000,
    foodCharges: 2500,
    deposit: 16000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Female",
    amenities: ["WiFi", "Meals", "Power Backup", "Housekeeping", "Laundry"],
    images: ["https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600"],
    safety: { cctv: true, guard: true, biometric: false },
    ratings: { room: 4.3, food: 4.4, owner: 4.6, wifi: 4.0 },
    reviews: [{ name: "Pooja", comment: "Auntiji bahut caring hain", rating: 5 }],
    ownerName: "Sunita Bora",
    ownerPhone: "9012340012",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Clement Town PG Near Army Cantonment",
    city: "Dehradun",
    locality: "Clement Town",
    type: "pg",
    rent: 8500,
    foodCharges: 2700,
    deposit: 17000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Power Backup", "Gym"],
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.4, food: 4.2, owner: 4.5, wifi: 4.1 },
    reviews: [{ name: "Manish", comment: "Shant area, bilkul sahi jagah", rating: 4 }],
    ownerName: "Colonel (Retd.) R.S. Panwar",
    ownerPhone: "9012340013",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Dharampur Gali No.5 PG",
    city: "Dehradun",
    locality: "Dharampur",
    type: "pg",
    rent: 7200,
    foodCharges: 2100,
    deposit: 14400,
    roomType: "Double",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Laundry", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600"],
    safety: { cctv: true, guard: false, biometric: false },
    ratings: { room: 4.0, food: 4.1, owner: 4.3, wifi: 3.9 },
    reviews: [{ name: "Tarun", comment: "Local market bilkul paas hai", rating: 4 }],
    ownerName: "Vijay Kandpal",
    ownerPhone: "9012340014",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Jakhan Premium PG",
    city: "Dehradun",
    locality: "Jakhan",
    type: "pg",
    rent: 14000,
    foodCharges: 4000,
    deposit: 28000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Parking", "Housekeeping", "Laundry"],
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.8, food: 4.5, owner: 4.9, wifi: 4.6 },
    reviews: [{ name: "Riya", comment: "Dehradun mein sabse acha PG!", rating: 5 }],
    ownerName: "Ashok Bhatt",
    ownerPhone: "9012340015",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Race Course Road Boys PG",
    city: "Dehradun",
    locality: "Race Course",
    type: "pg",
    rent: 10500,
    foodCharges: 3000,
    deposit: 21000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "AC", "Meals", "Gym", "Laundry"],
    images: ["https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600"],
    safety: { cctv: true, guard: true, biometric: false },
    ratings: { room: 4.5, food: 4.0, owner: 4.6, wifi: 4.4 },
    reviews: [{ name: "Yash", comment: "Greenery aur peaceful environment", rating: 5 }],
    ownerName: "Naresh Arora",
    ownerPhone: "9012340016",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Tapkeshwar Road Affordable PG",
    city: "Dehradun",
    locality: "Garhi Cantt",
    type: "pg",
    rent: 6800,
    foodCharges: 2000,
    deposit: 13600,
    roomType: "Triple",
    furnished: "Semi-Furnished",
    genderPreference: "Male",
    amenities: ["WiFi", "Meals", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=600"],
    safety: { cctv: false, guard: true, biometric: false },
    ratings: { room: 3.9, food: 4.0, owner: 4.2, wifi: 3.6 },
    reviews: [{ name: "Amit", comment: "Nature ke paas, fresh air milti hai", rating: 4 }],
    ownerName: "Bhola Nath Joshi",
    ownerPhone: "9012340017",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Survey Chowk Co-Living PG",
    city: "Dehradun",
    locality: "Survey Chowk",
    type: "pg",
    rent: 9000,
    foodCharges: 2800,
    deposit: 18000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Housekeeping", "Laundry"],
    images: ["https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600"],
    safety: { cctv: true, guard: false, biometric: true },
    ratings: { room: 4.3, food: 4.2, owner: 4.4, wifi: 4.1 },
    reviews: [{ name: "Kavya", comment: "City center mein, sab accessible hai", rating: 4 }],
    ownerName: "Seema Uniyal",
    ownerPhone: "9012340018",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Mussoorie Road View PG",
    city: "Dehradun",
    locality: "Mussoorie Road",
    type: "pg",
    rent: 11500,
    foodCharges: 3300,
    deposit: 23000,
    roomType: "Single",
    furnished: "Furnished",
    genderPreference: "Any",
    amenities: ["WiFi", "AC", "Meals", "Parking", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.7, food: 4.3, owner: 4.8, wifi: 4.4 },
    reviews: [{ name: "Ishaan", comment: "Mussoorie ka nazar, fresh hawa, amazing", rating: 5 }],
    ownerName: "Trilok Singh Rana",
    ownerPhone: "9012340019",
    residents: [DEFAULT_USER_ID],
  },
  {
    title: "Subhash Nagar Girls Premium PG",
    city: "Dehradun",
    locality: "Subhash Nagar",
    type: "pg",
    rent: 10000,
    foodCharges: 3000,
    deposit: 20000,
    roomType: "Double",
    furnished: "Furnished",
    genderPreference: "Female",
    amenities: ["WiFi", "AC", "Meals", "Laundry", "Housekeeping", "Power Backup"],
    images: ["https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=600"],
    safety: { cctv: true, guard: true, biometric: true },
    ratings: { room: 4.6, food: 4.5, owner: 4.9, wifi: 4.3 },
    reviews: [{ name: "Prachi", comment: "Girls ke liye ek number jagah, poori safety hai", rating: 5 }],
    ownerName: "Anita Maikhuri",
    ownerPhone: "9012340020",
    residents: [DEFAULT_USER_ID],
  },
];



async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ MongoDB connected");

  
    await Property.deleteMany({});
    console.log("🗑️  Old data cleared");

   
    const properties = await Property.insertMany(propertiesData);

  

    
    
   

    mongoose.disconnect();
  
  } catch (err) {
    console.error("❌ Error:", err.message);
    process.exit(1);
  }
}

seed();